module.exports=$={}
$["gl"]=x=>unshift(lines[shift()])
$["gi"]=x=>unshift(id())
$["gi\\"]=x=>unshift(unesc(id()))
$["gs"]=x=>unshift(form())
$["si"]=x=>ids[shift()]=shift()
$["::"]=x=>id()

$["el"]=x=>exec(lines[shift()])
$["es"]=x=>exec(shift())
$["ei"]=x=>exec(id())
$["e&"]=x=>($.swap(),shift()&&$.ei())
$["e|"]=x=>($.swap(),shift()||$.ei())

$["out"]=x=>process.stdout.write(''+shift())

$["e"]=x=>unshift(Math.E)
$["pi"]=x=>unshift(Math.PI)

$["E"]=x=>($.swap(),unshift(shift()*Math.pow(10,shift())))
$["_"]=x=>unshift(-shift())
$["+"]=x=>unshift(shift()- -shift())
$["-"]=x=>($.swap(),unshift(shift()-shift()))
$["*"]=x=>unshift(shift()*shift())
$["/"]=x=>($.swap(),unshift(shift()/shift()))
$["//"]=x=>($.swap(),unshift(Math.floor(shift()/shift())))
$["%"]=x=>($.swap(),unshift(mod(shift(),shift())))
$["/%"]=x=>($.over(),$.over(),$['//'](),$.rot_(),$['%']())
$["^"]=x=>($.swap(),unshift(Math.pow(shift(),shift())))
$["abs"]=x=>unshift(Math.abs(shift()))
$["sign"]=x=>unshift(Math.sign(shift()))
$["rand"]=x=>unshift(Math.random())
$["ln"]=x=>unshift(Math.log(shift()))
$["log"]=x=>unshift(Math.log10(shift()))
$["sin"]=x=>unshift(Math.sin(shift()))
$["cos"]=x=>unshift(Math.cos(shift()))
$["tan"]=x=>unshift(Math.tan(shift()))
$["sinh"]=x=>unshift(Math.sinh(shift()))
$["cosh"]=x=>unshift(Math.cosh(shift()))
$["tanh"]=x=>unshift(Math.tanh(shift()))
$["asin"]=x=>unshift(Math.asin(shift()))
$["acos"]=x=>unshift(Math.acos(shift()))
$["atan"]=x=>unshift(Math.atan(shift()))
$["asinh"]=x=>unshift(Math.asinh(shift()))
$["acosh"]=x=>unshift(Math.acosh(shift()))
$["atanh"]=x=>unshift(Math.atanh(shift()))
$["max"]=x=>unshift(Math.max(...stack[st]))
$["min"]=x=>unshift(Math.min(...stack[st]))
$["range"]=x=>($.swap(),unshift(...range(shift(),shift()).reverse()))

$["~"]=x=>unshift(~shift())
$["&"]=x=>($.swap(),unshift(shift()&shift()))
$["|"]=x=>($.swap(),unshift(shift()|shift()))
$["$"]=x=>($.swap(),unshift(shift()^shift()))

$["floor"]=x=>unshift(Math.floor(shift()))
$["trunc"]=x=>unshift(Math.trunc(shift()))
$["round"]=x=>unshift(Math.round(shift()))
$["ceil"]=x=>unshift(Math.ceil(shift()))

$["pick"]=x=>unshift(get(shift()))
$["nix"]=x=>splice(shift())
$["roll"]=x=>(x=get(0),$.pick(),unshift(x+1),$.nix())
$["roll_"]=x=>splice(shift(),0,shift())
$["dup"]=x=>unshift(stack[st][0])
$["drop"]=x=>shift()
$["rot"]=x=>unshift(splice(2,1)[0])
$["rot_"]=x=>($.rot(),$.rot())
$["swap"]=x=>($.dup(),$.rot_(),$.drop())
$["nip"]=x=>($.swap(),$.drop())
$["tuck"]=x=>($.dup(),$.rot_())
$["over"]=x=>($.swap(),$.tuck())
$["clr"]=x=>stack[st]=[]
$["rev"]=x=>stack[st].reverse()

$["split"]=x=>($.swap(),unshift(...shift().split(shift())))
$["join"]=x=>unshift(stack.join(shift()))

$["stack"]=x=>stack[st=shift()]||(stack[st]=[])
$["push"]=x=>stack[shift()].unshift(shift())
$["pull"]=x=>unshift(stack[shift()].shift())
$["len"]=x=>unshift(stack[st].length)
