export * as fs from 'fs'
export * as cp from 'child_process'
export * as _ from 'lodash'
export * as rls from 'readline-sync'
export * as $C from 'js-combinatorics'

export {default as parse} from './parser.js'
export {default as unesc} from './unesc.js'
export {default as INT} from './int.js'
export {default as SL} from './stdlib.js'