export * as fs from 'fs'
export * as cp from 'child_process'
export * as _ from 'lodash-es'
export * as rls from 'readline-sync'
export * as $C from 'js-combinatorics'
export * as itr from 'iter-tools-es'
export {default as chalk} from 'chalk'
export {runOnThread as mth} from 'funthreads'
export * as path from 'path'

export {default as parse} from './parser.js'
export {default as unesc} from './unesc.js'
export {default as INTRP} from './int.js'
export {default as SL} from './stdlib.js'